---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-docker-deployment
  labels:
    app: flask-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-docker
  template:
    metadata:
      labels:
        app: flask-docker
    spec:
      containers:
      - name: flask-docker-app
        image: adityadevops/flask-docker-app
        imagePullPolicy: Always
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-docker-service
spec:
  type: NodePort
  selector: 
    app: flask-docker
  ports:
  - port: 7000
    targetPort: 7000
    nodePort: 30007
  
  
