---
- hosts: all
  tasks:
  - name: copy manifests
    copy:
      src: kubernetes.yaml
      dest: /home/ansible/kubernetes/
  - name: Delete Kubernetes Objects
    shell: kubectl delete -f /home/ansible/kubernetes/kubernetes.yaml
    ignore_errors: True
  - name: Deploy Kubernetes Objects
    shell: kubectl apply -f /home/ansible/kubernetes/kubernetes.yaml
