---
- hosts: all
  tasks:
  - name: copy manifests
    copy:
      src: /home/ubuntu/workspace/jenkins-kubernetes/kubernetes.yaml
      dest: /home/ubuntu/
  - name: Delete Kubernetes Objects
    shell: kubectl delete -f /home/ubuntu/kubernetes.yaml
    ignore_errors: True
  - name: Deploy Kubernetes Objects
    shell: kubectl apply -f /home/ubuntu/kubernetes.yaml
