---
- hosts: all
  become: true
  tasks:
  - name: Delete Kubernetes Objects
    shell: kubectl delete -f kubernetes.yaml
    ignore_errors: True
  - name: Deploy Kubernetes Objects
    shell: kubectl apply -f kubernetes.yaml
