---
- hosts: all
  tasks:
  - name: copy manifests
    copy:
      src: kubernetes.yaml
      dest: /home/ansible/kubernetes/
  - name: Deploy Kubernetes Objects
    shell: kubectl apply -f /home/ansible/kubernetes/kubernetes.yaml
  - name: Update Deployment if image updated in Docker Hub
    command: kubectl rollout restart deployment.apps/flask-docker-deployment
